spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:rootpw@localhost:3306/miaosha?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
  redis:
    port: 6379
  profiles:
    active: dev
server:
  port: 8888
  servlet:
    context-path: /ms